cc_jobs/app/urls.py
from django.urls import path
from . import views

app_name='app'
urlpatterns=[

   path('/login',views.login,name='login'),
   path('/register',views.register,name='register'),
   # path('article/create',views.AddArticleView.as_view(),name='addarticleview'),
   # path('article/detail/<int:pk>',views.ArticleDetailView.as_view(),name='article_detail'),
   # path('article/delete/<int:pk>',views.ArticleDeleteView.as_view(),name='article_delete'),







]

cc_jobs/blog/urls.py
from django.urls import path
from . import views 
from .feeds import LatestPostsFeed


app_name = 'blog'
urlpatterns = [
    # post views
    path('', views.post_list, name='post_list'),
    # path('', views.PostListView.as_view(), name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/',
         views.post_detail,
         name='post_detail'),
    path('<int:post_id>/share/',
         views.post_share, name='post_share'),
    path('tag/<slug:tag_slug>/',
         views.post_list, name='post_list_by_tag'),
    path('feed/', LatestPostsFeed(), name='post_feed'),
    path('search/', views.post_search, name='post_search'),
]

cc_jobs/cc_jobs/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from courses.views	import	CourseListView
from app.views import ActivityViews



urlpatterns = [
     path('',ActivityViews.as_view(),name='activity_view'),
    # path('',views.ArticleViews.as_view(),name='articleview'),
    path('accounts/login/', auth_views.LoginView.as_view(), name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('admin/', admin.site.urls),
    path('course/', include('courses.urls',namespace='courses')),
    # path('list',	CourseListView.as_view(),	name='course_list'),

    path('students/', include('students.urls')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('app/',include('app.urls',namespace='app')),
    path('list', CourseListView.as_view(), name='course_list'),



]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

cc_jobs/courses/urls.py
from django.urls import path
from . import views
from courses.views import CourseListView


app_name='courses'
urlpatterns = [
    path('mine/',
         views.ManageCourseListView.as_view(),
         name='manage_course_list'),
    path('create/',
         views.CourseCreateView.as_view(),
         name='course_create'),
    path('<pk>/edit/',
         views.CourseUpdateView.as_view(),
         name='course_edit'),
    path('<pk>/delete/',
         views.CourseDeleteView.as_view(),
         name='course_delete'),
    path('<pk>/module/',
         views.CourseModuleUpdateView.as_view(),
         name='course_module_update'),
    path('module/<int:module_id>/content/<model_name>/create/',
         views.ContentCreateUpdateView.as_view(),
         name='module_content_create'),
    path('module/<int:module_id>/content/<model_name>/<id>/',
         views.ContentCreateUpdateView.as_view(),
         name='module_content_update'),
    path('content/<int:id>/delete/',
         views.ContentDeleteView.as_view(),
         name='module_content_delete'),
    path('module/<int:module_id>/',
         views.ModuleContentListView.as_view(),
         name='module_content_list'),
    path('module/order/',
         views.ModuleOrderView.as_view(),
         name='module_order'),
    path('content/order/',
         views.ContentOrderView.as_view(),
         name='content_order'),

    path('subject/<slug:subject>)/',
         views.CourseListView.as_view(),
         name='course_list_subject'),
    path('<slug:slug>/',
         views.CourseDetailView.as_view(),
         name='course_detail'),
    # path('list', CourseListView.as_view(), name='course_list'),
]

cc_jobs/app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from embed_video.fields import EmbedVideoField
from	django.template.loader	import	render_to_string
from	django.utils.safestring	import	mark_safe
# Create your models





class Activity(models.Model):
    name=models.CharField(max_length=23)
    # slug=models.CharField(max_length=40)
    description=models.TextField(max_length=7000)
    date_happen=models.DateField()
    image=models.ImageField()
    # video = EmbedVideoField()
    # def	render(self):
    #     return	render_to_string('app/content/{}.html'.format(self._meta.model_name),	{'activity': self})
    video= models.FileField(upload_to='videos/tigo')

cc_jobs/app/templates/app/layout.html
<!DOCTYPE html>
{% load static %}
{% load embed_video_tags %}
<html lang="en">
       <head>
         <meta charset="utf-8">
         <meta http-equiv="X-UA-Compatible" content="IE=edge">
         <meta name="viewport" content="width=device-width, initial-scale=1">
         <title>Title Page</title>

         <!-- Bootstrap CSS -->
         <link href="{% static 'bootstrap.min.css' %}" rel="stylesheet">
         <link href="{% static 'style.css' %}" rel="stylesheet">

         <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
         <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
         <!--[if lt IE 9]>
         <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
         <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
         <![endif]-->
       </head>
       <body>
               <nav class="navbar navbar-inverse navbar-fixed-top  " role="navigation">
         <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">
                 <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                 </button>
                 <a class="navbar-brand" href="#">CC-JOBS</a>
          </div>

         <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse navbar-ex1-collapse ">
                 <ul class="nav navbar-nav nav1">

                  <!-- <li><a href="#" class="active">About Us</a></li> -->
                  <!-- <li><a href="#">join us</a></li> -->
                <li class="dropdown">
                   <a href="#" class="dropdown-toggle" data-toggle="dropdown">About Us </a>
                   <ul class="dropdown-menu">
                    <li><a href="#">Purpose & Vision</a></li>
                    <li><a href="#">Our Activities</a></li>
                    <li><a href="#">Rwanda Slums</a></li>
                    <li><a href="#">Our Team</a></li>
                    <li><a href="#">Partnerships</a></li>
                    <li><a href="#">Important Stakeholders</a></li>
                    <li><a href="#">Our Funders</a></li>
                    <li><a href="#">Contact Us</a></li>
                   </ul>
                 </li>




                  <!-- <li><a href="#">Training Programs</a></li> -->
                  <li class="dropdown">
                     <a href="#" class="dropdown-toggle" data-toggle="dropdown">Training Programs</a>
                     <ul class="dropdown-menu">
                      <li><a href="#">Method and Approach</a></li>
                      <li><a href="#">Culinary Arts and Nutrition</a></li>
                      <li><a href="#">Construction Engineering</a></li>

                     </ul>
                   </li>





                  <!-- <li><a href="#">Student Exchange Program</a></li> -->
                  <li class="dropdown">
                     <a href="#" class="dropdown-toggle" data-toggle="dropdown">Student Exchange Program</a>
                     <ul class="dropdown-menu">
                      <li><a href="#">Internship Programs</a></li>
                      <li><a href="#">Included Arrangements and Prices</a></li>
                      <li><a href="#">Funding Campaign</a></li>
                      <li><a href="#">Exploration</a></li>
                      <li><a href="#">Support Social Development</a></li>

                     </ul>
                   </li>





                  <!-- <li><a href="#">Impact</a></li> -->
                  <li class="dropdown">
                     <a href="#" class="dropdown-toggle" data-toggle="dropdown">Impact</a>
                     <ul class="dropdown-menu">
                      <li><a href="#">Results</a></li>
                      <li><a href="#">Success Stories</a></li>
                      <li><a href="#">Current activities</a></li>

                     </ul>
                   </li>



                  <!-- <li><a href="#">Get Involved</a></li> -->
                  <li class="dropdown">
                     <a href="#" class="dropdown-toggle" data-toggle="dropdown">Get Involved</a>
                     <ul class="dropdown-menu">
                      <li><a href="#">Volunteering</a></li>
                      <li><a href="#">Professional exchange</a></li>
                      <li><a href="#">Join Our Team</a></li>
                      <li><a href="#">Partner with Us</a></li>
                      <li><a href="#">Financial support</a></li>

                     </ul>
                   </li>



                  <li><a href="{% url 'blog:post_list'%}">Blog</a></li>
                  <li><a href="{% url 'course_list' %}">Courses</a></li>

                  <li><a href="{% url 'courses:manage_course_list' %}">Instructor</a></li>

                 </ul>

                 <ul class="nav navbar-nav navbar-right">
                  <!-- <li><a href="#">join us</a></li> -->
                  <!--<li class="dropdown">
                   <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
                   <ul class="dropdown-menu">
                    <li><a href="#">Action</a></li>
                    <li><a href="#">Another action</a></li>
                    <li><a href="#">Something else here</a></li>
                    <li><a href="#">Separated link</a></li>
                   </ul>
                 </li>-->
                 </ul>
          </div><!-- /.navbar-collapse -->
               </nav>
          

            <div class="container-fluid">


              <div class="container">

      <div id="myCarousel" class="carousel slide" data-ride="carousel">
        <!-- Indicators -->
        <ol class="carousel-indicators">
          <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
          <li data-target="#myCarousel" data-slide-to="1"></li>
          <li data-target="#myCarousel" data-slide-to="2"></li>
        </ol>

        <!-- Wrapper for slides -->
        <div class="carousel-inner">

          <div class="item active">
            <img src="{% static 'cristiano.jpg'%}" alt="gitega" style="width:100%;" >
            <div class="carousel-caption">
              <h3>gitega</h3>
              <p>gitega is always so much fun!</p>
            </div>
          </div>

          <div class="item">
            <img src="{% static 'cristiano.jpg'%}" alt="Nyamirambo" style="width:100%;" >
            <div class="carousel-caption">
              <h3>Nyamirambo</h3>
              <p>Thank you people</p>
            </div>
          </div>

          <div class="item">
            <img src="{% static 'cristiano.jpg'%}" alt="Remera" style="width:100%;" >
            <div class="carousel-caption">
              <h3>Remera</h3>
              <p>We love the Big Apple!</p>
            </div>
          </div>

        </div>

        <!-- Left and right controls -->
        <a class="left carousel-control" href="#myCarousel" data-slide="prev">
          <span class="glyphicon glyphicon-chevron-left"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#myCarousel" data-slide="next">
          <span class="glyphicon glyphicon-chevron-right"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
    </div>










             <div class="container">




               <br>
               <br>
















          <br>
          <br>
          <br>
          <br>

            <div class="row activ">
              <h2>RECENT ACTIVITIES</h2>
              {% for activity in activity_list %}
              <div class="row">



                  <div class="col-md-7">
                    <div class="row">
                      <div class="col-md-5">
                         <img src="{{activity.image.url }}"class="thumbnail" alt="">
                      </div>
                      <div class="col-md-offset-1 col-md-6">
                        <h3>{{activity.name}}</h3>
                         <p>{{ activity.description}}</p>

                      </div>

                    </div>




            </div>
            <div class="col-md-4 col-md-offset-1">

              <video src="{{activity.video.url}}"  poster="posterimage.jpg" class="thumbnail" controls >

              </video>

            </div>
            </div>
            <br>
            <br>
            {% endfor %}



          <br>
          <br>

            <div class="row conus">
              <h2>CONTACT US</h2>
              <div class="col-md-8 col-md-offset-1">
                Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                 Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
              </div>


              </div>
            </div>

          </div>
            </div>


            <!--{% for act in activity_list %}
             <video width="320" height="240" controls>
               <source src="{% static "{{MEDIA_URL}}/videos/{{act.video}}" %}" type="video/mkv">
                 </video>
                {% endfor %}-->






        <!-- jQuery -->
        <script src="{% static 'jquery-3.3.1.min.js' %}"></script>
        <!-- Bootstrap JavaScript -->
        <script src="{% static 'bootstrap.min.js ' %}"></script>
  <!-- Your own javascript -->
  <script src="{% static 'project.js' %}">

  </script>
       </body>
</html>